apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-svc.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "api-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and  (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-svc.selectorLabels" . | nindent 4 }}
