# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_call:

jobs:

  build-test-api-svc:

    name: Build and Test api-svc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          pushd api-svc
          sed -i 's/zsh/bash/g' run_dev_venv.sh
          python -m pip install --upgrade pip
          source ./run_dev_venv.sh
          popd

      - name: Run Lint and Tests
        run: |
          pushd api-svc
          source venv/bin/activate
          sed -i 's/zsh/bash/g' run_tests_lint_format.sh
          ./run_tests_lint_format.sh
          popd
