# This workflow builds a container image using docker buildx

name: Container Image Build

on:
  workflow_call:

jobs:

  build-container-image:

    name: Build Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container Image with Docker
        uses: docker/build-push-action@v3
        with:
          context: api-svc
          push: false
          tags: user/app:latest
