# This workflow builds a container and then publishes it with tags.

name: Container Image Build

on:
  workflow_call:
    secrets:
      username:
        description: "Docker Hub Username passed from the caller workflow"
        required: true
      usertoken:
        description: "Docker hub user token passed from the caller workflow"
        required: true

jobs:

  publish-container-image:

    name: Publish Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.usertoken }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container Image with Docker
        uses: docker/build-push-action@v3
        with:
          context: api-svc
          push: true
          tags: adrielp/api-svc:latest

